import { PackageAudience, PackageBillingCycle, SubscriptionType } from "@prisma/client";

export const batchData = [
  {
    title: 'Scholar',
    description: 'Top 10% in 5 courses',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/132516.png',
    category: 'Milestone',
    rarity: 'Epic',
  },
  {
    title: 'Time Master',
    description: 'Complete 100 learning hours',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/225545.png',
    category: 'Milestone',
    rarity: 'Rare',
  },
  {
    title: 'Knowledge Seeker',
    description: 'Complete 5 courses in different categories',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/637753.png',
    category: 'Milestone',
    rarity: 'Uncommon',
  },
  {
    title: 'Certificate Collector',
    description: 'Earn 5 certificates',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/901949.png',
    category: 'Milestone',
    rarity: 'Rare',
  },
  {
    title: 'Feedback Champion',
    description: 'Submit 5 actionable feedbacks',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/424122.png',
    category: 'Innovation',
    rarity: 'Uncommon',
  },
  {
    title: 'Innovation Leader',
    description: 'Complete 5 innovation courses',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/909791.png',
    category: 'Innovation',
    rarity: 'Epic',
  },
  {
    title: 'Change Architect',
    description: 'Complete 3 innovation courses',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/722002.png',
    category: 'Innovation',
    rarity: 'Rare',
  },
  {
    title: 'Communication',
    description: 'Finish 5 communications courses',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/826744.png',
    category: 'Skills',
    rarity: 'Uncommon',
  },
  {
    title: 'Project Management',
    description: 'Complete 5 project management courses',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/594141.png',
    category: 'Skills',
    rarity: 'Epic',
  },
  {
    title: 'Leadership',
    description: 'Finish 5 leadership courses',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/968016.png',
    category: 'Skills',
    rarity: 'Epic',
  },
  {
    title: 'Problem Solver',
    description: 'Finish 50 challenges',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/754199.png',
    category: 'Skills',
    rarity: 'Uncommon',
  },
  {
    title: 'Community Champion',
    description: 'Participate in 15 discussions',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/401825.png',
    category: 'Community',
    rarity: 'Uncommon',
  },
  {
    title: 'Dialogue Leader',
    description: 'Create 10 discussion topics',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/424035.png',
    category: 'Community',
    rarity: 'Rare',
  },
  {
    title: 'Mentor',
    description: 'Finish 5 Human resource courses',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/846859.png',
    category: 'Community',
    rarity: 'Epic',
  },
  {
    title: 'Top Contributor',
    description: '10 helpful forum answers',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/803609.png',
    category: 'Community',
    rarity: 'Uncommon',
  },
  {
    title: 'Polyglot',
    description: '3 different programming languages',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/991611.png',
    category: 'Specialization',
    rarity: 'Rare',
  },
  {
    title: 'Cybersecurity Expert',
    description: 'Complete Cybersecurity path',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/849879.png',
    category: 'Specialization',
    rarity: 'Epic',
  },
  {
    title: 'AI Specialist',
    description: 'Complete AI path',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/104011.png',
    category: 'Specialization',
    rarity: 'Epic',
  },
  {
    title: 'Mobile Developer',
    description: 'Complete Mobile Development path',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/135220.png',
    category: 'Specialization',
    rarity: 'Rare',
  },
  {
    title: 'Web Developer',
    description: 'Complete Web Development path',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/118688.png',
    category: 'Specialization',
    rarity: 'Rare',
  },
  {
    title: 'Data Scientist',
    description: 'Complete Data Science path',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/348254.png',
    category: 'Specialization',
    rarity: 'Rare',
  },
  {
    title: 'Consistent Learner',
    description: 'Active learning on 10 days',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/221900.png',
    category: 'Engagement',
    rarity: 'Common',
  },
  {
    title: 'Milestone Achiever',
    description: 'Finnish 5 courses in 3 months',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/917426.png',
    category: 'Engagement',
    rarity: 'Rare',
  },
  {
    title: 'Streak Champion',
    description: '60 days learning streak',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/962613.png',
    category: 'Engagement',
    rarity: 'Rare',
  },
  {
    title: 'Social Learner',
    description: 'Join 5 study groups',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/137143.png',
    category: 'Engagement',
    rarity: 'Common',
  },
  {
    title: 'Learning Resilience',
    description: 'Improve quiz score by ≥50%',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/839649.png',
    category: 'Quiz & Assessment',
    rarity: 'Uncommon',
  },
  {
    title: 'Perfect Score',
    description: 'Achieve 100% on 3 quizzes',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/477613.png',
    category: 'Quiz & Assessment',
    rarity: 'Uncommon',
  },
  {
    title: 'First Pass Mastery',
    description: '100% score on first attempt (5 quizzes)',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/475063.png',
    category: 'Quiz & Assessment',
    rarity: 'Common',
  },
  {
    title: 'Quiz Master',
    description: 'Score ≥90% on 10 quizzes',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/741616.png',
    category: 'Quiz & Assessment',
    rarity: 'Rare',
  },
  {
    title: 'Quick Starter',
    description: 'Complete first course within 24 hours',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/647257.png',
    category: 'Achievement',
    rarity: 'Common',
  },
  {
    title: 'Speed Runner',
    description: 'Finish a course in under 2 hours',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/251110.png',
    category: 'Achievement',
    rarity: 'Uncommon',
  },
  {
    title: 'Marathon Learner',
    description: 'Complete 50 courses',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/904306.png',
    category: 'Achievement',
    rarity: 'Epic',
  },
  {
    title: 'Course Completions',
    description: 'Complete 10 courses',
    logo: 'https://emonhassan.s3.ap-southeast-1.amazonaws.com/images/batch/logo/807131.png',
    category: 'Achievement',
    rarity: 'Common',
  },
];

export const packageData = [
  {
    title: 'Enterprise',
    type: SubscriptionType.enterprise,
    audience: PackageAudience.company_admin,
    features: [
      'Big Enterprises',
      '5 Instructors',
      '3000 Active Learners',
      '50 GB storage',
      'Course Builder',
      'Create Free Courses',
      'Sell paid courses',
      'Sell course bundles',
      'Create events',
      'Sell event tickets',
      'Sell online books',
      '5 Co-Instructors',
      'Transaction Fee (5 %)',
      'Custom Certificates',
      'Quizzes & Assignments',
      'Zoom Integration - Live session',
      'Marketing Tools (Coupons, promotion)',
      'Exclusive courses for students',
      'Affiliate links',
      'Advanced support',
    ],
    billingCycle: PackageBillingCycle.annually,
    price: 35400,
    popularity: 0,
  },
  {
    title: 'Enterprise',
    type: SubscriptionType.enterprise,
    audience: PackageAudience.company_admin,
    features: [
      'Big Enterprises',
      '5 Instructors',
      '3000 Active Learners',
      '50 GB storage',
      'Course Builder',
      'Create Free Courses',
      'Sell paid courses',
      'Sell course bundles',
      'Create events',
      'Sell event tickets',
      'Sell online books',
      '5 Co-Instructors',
      'Transaction Fee (5 %)',
      'Custom Certificates',
      'Quizzes & Assignments',
      'Zoom Integration - Live session',
      'Marketing Tools (Coupons, promotion)',
      'Exclusive courses for students',
      'Affiliate links',
      'Advanced support',
    ],
    billingCycle: PackageBillingCycle.monthly,
    price: 2999,
    popularity: 0,
  },
  {
    title: 'SME',
    type: SubscriptionType.sme,
    audience: PackageAudience.company_admin,
    features: [
      'Small and medium Companies',
      '3 Instructors',
      '1500 Active Learners',
      '20 GB storage',
      'Course Builder',
      'Create Free Courses',
      'Sell paid courses',
      'Sell course bundles',
      'Create events',
      'Sell event tickets',
      'Sell online books',
      '3 Co-Instructors',
      'Transaction Fee (10%)',
      'Platform-Branded Certificates',
      'Quizzes & Assignments',
      'Zoom Integration - Live session',
      'Marketing Tools (Coupons, promotion)',
      'Exclusive courses for students',
      'Basic support',
    ],
    billingCycle: PackageBillingCycle.annually,
    price: 11400,
    popularity: 0,
  },
  {
    title: 'SME',
    type: SubscriptionType.sme,
    audience: PackageAudience.company_admin,
    features: [
      'Small and medium Companies',
      '3 Instructors',
      '1500 Active Learners',
      '20 GB storage',
      'Course Builder',
      'Create Free Courses',
      'Sell paid courses',
      'Sell course bundles',
      'Create events',
      'Sell event tickets',
      'Sell online books',
      '3 Co-Instructors',
      'Transaction Fee (10%)',
      'Platform-Branded Certificates',
      'Quizzes & Assignments',
      'Zoom Integration - Live session',
      'Marketing Tools (Coupons, promotion)',
      'Exclusive courses for students',
      'Basic support',
    ],
    billingCycle: PackageBillingCycle.monthly,
    price: 999,
    popularity: 0,
  },
  {
    title: 'NGO',
    type: SubscriptionType.ngo,
    audience: PackageAudience.company_admin,
    features: [
      'Community orgs and associations',
      '2 Instructors',
      '1000 Active Learners',
      '10 GB storage',
      'Course Builder',
      'Create Free Courses',
      'No paid courses',
      'Create Events',
      '3 Co-Instructors',
      'Platform-Branded Certificates',
      'Quizzes & Assignments',
      'Zoom Integration - Live session',
      'Exclusive courses for students',
      'Basic support',
    ],
    billingCycle: PackageBillingCycle.annually,
    price: 5400,
    popularity: 0,
  },
  {
    title: 'NGO',
    type: SubscriptionType.ngo,
    audience: PackageAudience.company_admin,
    features: [
      'Community orgs and associations',
      '2 Instructors',
      '1000 Active Learners',
      '10 GB storage',
      'Course Builder',
      'Create Free Courses',
      'No paid courses',
      'Create Events',
      '3 Co-Instructors',
      'Platform-Branded Certificates',
      'Quizzes & Assignments',
      'Zoom Integration - Live session',
      'Exclusive courses for students',
      'Basic support',
    ],
    billingCycle: PackageBillingCycle.monthly,
    price: 499,
    popularity: 0,
  },
  {
    title: 'Premium',
    type: SubscriptionType.premium,
    audience: PackageAudience.instructor,
    features: [
      'For Professional Instructors',
      '1 Instructor',
      '10 GB storage',
      'Course Builder',
      'Create Free Courses',
      'Sell paid courses',
      'Five Co-Instructors',
      'Transaction Fee (15 %)',
      'Custom Certificates',
      'Quizzes & Assignments',
      'Zoom Integration - Live session',
      'Create Events',
      'Marketing Tools (Coupons, promotion)',
      'Affiliate link',
      'Advanced support',
    ],
    billingCycle: PackageBillingCycle.annually,
    price: 840,
    popularity: 0,
  },
  {
    title: 'Premium',
    type: SubscriptionType.premium,
    audience: PackageAudience.instructor,
    features: [
      'For Professional Instructors',
      '1 Instructor',
      '10 GB storage',
      'Course Builder',
      'Create Free Courses',
      'Sell paid courses',
      'Five Co-Instructors',
      'Transaction Fee (15 %)',
      'Custom Certificates',
      'Quizzes & Assignments',
      'Zoom Integration - Live session',
      'Create Events',
      'Marketing Tools (Coupons, promotion)',
      'Affiliate link',
      'Advanced support',
    ],
    billingCycle: PackageBillingCycle.monthly,
    price: 79,
    popularity: 0,
  },
  {
    title: 'Standard',
    type: SubscriptionType.standard,
    audience: PackageAudience.instructor,
    features: [
      'For Growing Instructors',
      '1 Instructor',
      '5 GB storage',
      'Course Builder',
      'Create Free Courses',
      'Sell paid courses',
      'One Co-Instructors',
      'Transaction Fee (25%)',
      'Basic Certificates',
      'Quizzes & Assignments',
      'Marketing Tools (Coupons, promotion)',
      'Basic support',
    ],
    billingCycle: PackageBillingCycle.annually,
    price: 300,
    popularity: 0,
  },
  {
    title: 'Standard',
    type: SubscriptionType.standard,
    audience: PackageAudience.instructor,
    features: [
      'For Growing Instructors',
      '1 Instructor',
      '5 GB storage',
      'Course Builder',
      'Create Free Courses',
      'Sell paid courses',
      'One Co-Instructors',
      'Transaction Fee (25%)',
      'Basic Certificates',
      'Quizzes & Assignments',
      'Marketing Tools (Coupons, promotion)',
      'Basic support',
    ],
    billingCycle: PackageBillingCycle.monthly,
    price: 29,
    popularity: 0,
  },
  {
    title: 'Basic',
    type: SubscriptionType.basic,
    audience: PackageAudience.instructor,
    features: [
      'For new instructors',
      '1 Instructors',
      '500MB storage',
      'Course Build',
      'Create Free Courses',
      'Quizzes',
      'Basic support',
    ],
    billingCycle: PackageBillingCycle.monthly,
    price: 0,
    popularity: 0,
  },
  {
    title: 'Basic',
    type: SubscriptionType.basic,
    audience: PackageAudience.instructor,
    features: [
      'For new instructors',
      '1 Instructors',
      '500MB storage',
      'Course Builder',
      'Create Free Courses',
      'Quizzes',
      'Basic support',
    ],
    billingCycle: PackageBillingCycle.annually,
    price: 0,
    popularity: 1,
  },
];